import Head from 'next/head'
import Navbar from './src/components/NavBar'
import LandingPage from './src/components/landing/LandingPage'
import AtendimentoOnline from './src/components/atendimento/atendimento'
import Wave1 from './src/components/waves/Wave1'
import Wave2 from './src/components/waves/Wave2'
import Wave3 from './src/components/waves/Wave3'
import Terapia from './src/components/terapia/terapia'
import Sobre from './src/components/sobre/sobre'

export default function Home() {
  return (
    <>
      <Head>
        <title>Psicóloga Online | Dara Marques</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <LandingPage />
      <Wave2 />
      <AtendimentoOnline />
      <Wave1 />
      <Terapia />
      <Wave3 />
      <Sobre />

      {/*  <a href="https://wa.me/message/OQPASIZH7O75G1" target="_blank"  rel="noopener noreferrer" style={{ position: 'fixed', bottom: '20px', right: '30px', zIndex: '9999' }}>
        <img src="/whatsapp.svg"  />
      </a> */}
      {/*   <div id="footer" className="footer">
                    <div className={isMobile ? "" : "container"}>
                        <div className="footer-brand">
                            <img height={70} style={{filter: "color(""/)"}} width={70} src="./logoDara.svg"/>
                        </div>
                   
                     
                    </div>
                </div> */}


      {/*   <footer className="pb-2 mb-2" style={{ background: "#d0b3b5", color: "black", textAlign: "center" }}>
                    <hr className="mt-0"></hr>
                    <span className="text-muted small">
                        Powered by{' '} 
                        <a target={'_blank'} href="https://lanisystems.vercel.app"><img width={110} src='./lani-5andar2.svg'></img></a>
                    </span>
                </footer> */}
    </>
  )
}
